services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-project.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/98-xdebug.ini:ro
    environment:
      XDEBUG_MODE: off
    depends_on:
      - postgres
      - redis
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - appnet

  postgres:
    build:
      context: ./docker/postgres
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "${POSTGRES_PORT:-54322}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-63790}:6379"
    volumes:
      - redisdata:/data
    networks:
      - appnet

  mailpit:
    image: axllent/mailpit:latest
    container_name: laravel_mailpit
    ports:
      - "${MAILPIT_PORT:-8025}:8025"
    networks:
      - appnet

  node:
    image: node:20-alpine
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - appnet

volumes:
  pgdata:
  redisdata:

networks:
  appnet:
    driver: bridge
